# Generated by Django 5.0.6 on 2024-06-03 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('alumno', models.CharField(max_length=100)),
                ('tema', models.CharField(max_length=100)),
                ('patrocinio', models.BooleanField(default=False)),
                ('profesor', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
            },
        ),
    ]
