# Generated by Django 5.0.6 on 2024-06-03 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alumno_profesor_alter_proyecto_alumno_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesor',
            options={'verbose_name': 'Profesor', 'verbose_name_plural': 'Profesores'},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
    ]
