# Generated by Django 5.0.6 on 2024-06-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_profesor_options_alter_proyecto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='alumno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='profesor',
            field=models.CharField(max_length=100),
        ),
    ]
