# Generated by Django 5.0.6 on 2024-06-03 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_proyecto_alumno_alter_proyecto_profesor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Proyectos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Profesor', to=settings.AUTH_USER_MODEL),
        ),
    ]
