# Generated by Django 5.0.6 on 2024-06-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_proyecto_alumno_alter_proyecto_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='profesor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
