# Generated by Django 5.0.6 on 2024-06-03 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_proyecto_alumno_alter_proyecto_profesor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='profesor',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='nombre_proyecto',
            field=models.CharField(default='Nombre', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='profesor_patrocinador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_patrocinados', to=settings.AUTH_USER_MODEL),
        ),
    ]
